### ISSUE TITLE
Error cpuminer-config.h

### ISSUE THREAD

**Issue by muzaffer652** [OttyLab/BitZenyAndroidMiningLibrary#21]
Error:(27, 10) fatal error: 'cpuminer-config.h' file not found

can you help me?

**Comment by OttyLab** [comment]
#20 fixes that issue, I suppose. Could you pull the latest master branch?

**Comment by muzaffer652** [comment]
fixed, Thank you

**Comment by muzaffer652** [comment]
What coins can I mining except BitZeny?

**Comment by OttyLab** [comment]
Currently, the library runs yescrypt for BitZeny only. If an interface to select hash algorithm is prepared, scrypt (LiteCoin) and SHA256 (Bitcoin) mining would be available (not tested).
