### ISSUE TITLE
Build error on latest Android Studio & NDK

### ISSUE THREAD

**Issue by minkcrypto-zz** [OttyLab/BitZenyAndroidMiningLibrary#37]
+ Windows 10
+ Android Studio 3.4.2

![capture](https://user-images.githubusercontent.com/50817233/61176710-9914d180-a600-11e9-8c79-bc8991e15a09.PNG)

I was unable to change "Build Variants" for bitzenymininglibrary also ( SDK doesn't allowed me to change them ).

Any tips?

**Comment by minkcrypto-zz** [comment]
I've also updated submodules using `git clone --recurse-submodules` but no success.

**Comment by minkcrypto-zz** [comment]
OK, it is very awkward but I was able to solve this issue by clicking "remove selected".

**Comment by OttyLab** [comment]
@minkcrypto 
Sorry, I did not notice this issue. I think `./idea/modules.xml` should be excluded.

**Comment by minkcrypto-zz** [comment]
Thank you for your great tip!
